spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/aneka_kemeja
      username: postgres
      password: Testing1
      driver-class-name: org.postgresql.Driver
      hikari:
        connection-timeout: 3000
        idle-timeout: 600000
        max-lifetime: 180000
    jpa:
      hibernate:
        ddl-auto: update
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
    application:
        name: backend_backoffice
server:
  port: 8081